// Single source of truth for pinned native runtime versions + per-platform
// download integrity. The data lives in runtime-catalog.json at the repo root
// (generated by scripts/sync-runtime-catalog.mjs from the installed deps) and
// is embedded here at compile time. The managed-runtime installer
// (commands/runtime.rs), the bundled-runtime resolvers (commands/claude.rs,
// codex_app_server.rs, sidecar.rs) and the Node sidecar all read from this one
// catalog so their versions never drift apart.

use serde::Deserialize;
use std::collections::HashMap;
use std::sync::OnceLock;

const RUNTIME_CATALOG_JSON: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../runtime-catalog.json"
));

#[derive(Debug, Deserialize)]
pub struct RuntimeCatalog {
    pub claude: ClaudeSection,
    pub codex: CodexSection,
    pub node: NodeSection,
}

#[derive(Debug, Deserialize)]
pub struct ClaudeSection {
    pub version: String,
    pub platforms: HashMap<String, ClaudePlatform>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ClaudePlatform {
    pub package_name: String,
    pub integrity: String,
}

#[derive(Debug, Deserialize)]
pub struct CodexSection {
    pub version: String,
    pub platforms: HashMap<String, CodexPlatform>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CodexPlatform {
    pub npm_version: String,
    pub integrity: String,
}

#[derive(Debug, Deserialize)]
pub struct NodeSection {
    pub version: String,
    pub platforms: HashMap<String, NodePlatform>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NodePlatform {
    pub node_platform: String,
    pub node_arch: String,
    pub archive_ext: String,
    pub exe_path: String,
    pub sha256: String,
}

fn catalog() -> &'static RuntimeCatalog {
    static CATALOG: OnceLock<RuntimeCatalog> = OnceLock::new();
    CATALOG.get_or_init(|| {
        serde_json::from_str(RUNTIME_CATALOG_JSON)
            .expect("runtime-catalog.json is embedded at build time and must be valid JSON")
    })
}

pub fn claude_version() -> &'static str {
    &catalog().claude.version
}

pub fn codex_version() -> &'static str {
    &catalog().codex.version
}

pub fn node_version() -> &'static str {
    &catalog().node.version
}

pub fn claude_platform(key: &str) -> Option<&'static ClaudePlatform> {
    catalog().claude.platforms.get(key)
}

pub fn codex_platform(key: &str) -> Option<&'static CodexPlatform> {
    catalog().codex.platforms.get(key)
}

pub fn node_platform(key: &str) -> Option<&'static NodePlatform> {
    catalog().node.platforms.get(key)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn embedded_catalog_parses_and_covers_all_platforms() {
        let keys = [
            "darwin-arm64",
            "darwin-x64",
            "linux-arm64",
            "linux-x64",
            "win32-arm64",
            "win32-x64",
        ];
        for key in keys {
            assert!(claude_platform(key).is_some(), "claude missing {key}");
            assert!(codex_platform(key).is_some(), "codex missing {key}");
            assert!(node_platform(key).is_some(), "node missing {key}");
        }
        assert!(!claude_version().is_empty());
        assert!(!codex_version().is_empty());
        assert!(!node_version().is_empty());

        // Codex platform versions carry the platform suffix.
        let codex = codex_platform("darwin-arm64").unwrap();
        assert_eq!(
            codex.npm_version,
            format!("{}-darwin-arm64", codex_version())
        );
    }
}
